### PR TITLE
Register action to create zip from multiple files

### PR DESCRIPTION
**Pull request by juliushaertl**
Implements #1

image
image
133/117784528-f51fff80-b243-11eb-8878-bd6b2ad96dfe.png)

Needs some further improvements on the following points
- Better description of what is happening and on success/failure
- Think about handling the default file name of the output zip archive

In theory this would work fine without any webpack and just plain javascript but then we'd need to use deprecated global functions so I decided to pull in the build pipeline

Requires https://github.com/nextcloud/server/pull/26941

### CODE REVIEW

**Comment by juliushaertl** [comment]
The notification is actually wrong as https://github.com/nextcloud/files_zip/issues/2 is still missing

**Review by rullzer — APPROVED** [review]
Seems to do the trick. Yes we need to add some stuff but small steps

**Comment by jancborchardt** [comment]
@juliushaertl is it possible to move this below the "Download" action? Cause "Copy or move" and "Download" are more common actions than this one. :)

**Comment by juliushaertl** [comment]
@jancborchardt Yes, mind to open an issue for that?

**Pull request merged**
